// <auto-generated />

namespace TestingSystem.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    /// <summary>
    /// Defines the <see cref="Modified13team1v10" />
    /// </summary>
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Modified13team1v10 : IMigrationMetadata
    {
        /// <summary>
        /// Defines the Resources
        /// </summary>
        private readonly ResourceManager Resources = new ResourceManager(typeof(Modified13team1v10));

        /// <summary>
        /// Gets the Id
        /// </summary>
        string IMigrationMetadata.Id
        {
            get { return "201903010226097_Modified13team1v1.0"; }
        }

        /// <summary>
        /// Gets the Source
        /// </summary>
        string IMigrationMetadata.Source
        {
            get { return null; }
        }

        /// <summary>
        /// Gets the Target
        /// </summary>
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
